package auth

import "testing"

// These fixtures were generated by the actual installed Werkzeug 3.1.8
// (werkzeug.security.generate_password_hash) for the password
// "correct horse battery staple", to prove Go verification is byte-for-byte
// compatible with the real hashes stored in users.db.
func TestCheckPasswordHashWerkzeugFixtures(t *testing.T) {
	const password = "correct horse battery staple"
	const wrongPassword = "not the password"

	cases := []struct {
		name string
		hash string
	}{
		{"scrypt default", "scrypt:32768:8:1$PfpUFPgbk8X2hmC8$b1a418388a399309523e5b38d84994301cf59a518aee3cdf8060c6e911a3ea0d9a51be436234e632a75b94c755cc5a598b7ee9a0cb0efaa65a30721e873acb9d"},
		{"pbkdf2 sha256 1000000", "pbkdf2:sha256:1000000$QDvS8l60YzsLYJ3P$de990b50f2b320187413579f7bab9206431cdaba86a93afcf4c904a73f600be2"},
		{"pbkdf2 sha1 29000", "pbkdf2:sha1:29000$xvNkVDgiqhxcvqq0$f2631c85407d5ec5d330297b7fc1e3d153f04d39"},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if !CheckPasswordHash(c.hash, password) {
				t.Fatalf("expected correct password to verify against %s", c.name)
			}
			if CheckPasswordHash(c.hash, wrongPassword) {
				t.Fatalf("expected wrong password to fail verification against %s", c.name)
			}
		})
	}
}

func TestCheckPasswordHashMalformed(t *testing.T) {
	cases := []string{"", "no-dollar-signs", "method$saltonly", "unknownmethod$salt$hash"}
	for _, h := range cases {
		if CheckPasswordHash(h, "anything") {
			t.Fatalf("expected malformed hash %q to fail verification", h)
		}
	}
}

func TestGeneratePasswordHashRoundTrips(t *testing.T) {
	h, err := GeneratePasswordHash("a fresh password")
	if err != nil {
		t.Fatal(err)
	}
	if !CheckPasswordHash(h, "a fresh password") {
		t.Fatalf("expected freshly generated hash to verify, got hash %q", h)
	}
	if CheckPasswordHash(h, "wrong password") {
		t.Fatal("expected wrong password to fail verification against freshly generated hash")
	}
}
