package mysqldb

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseOptionFileTCP(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "my.cnf")
	fixture := `# generated by openpanel installer
[client]
user=openpanel
password=not-a-real-secret
host=127.0.0.1
port=3306
database=panel

[mysql]
prompt="panel> "
`
	if err := os.WriteFile(path, []byte(fixture), 0600); err != nil {
		t.Fatal(err)
	}

	values, err := parseOptionFile(path, "client")
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"user":     "openpanel",
		"password": "not-a-real-secret",
		"host":     "127.0.0.1",
		"port":     "3306",
		"database": "panel",
	}
	for k, v := range want {
		if values[k] != v {
			t.Fatalf("key %q: expected %q, got %q", k, v, values[k])
		}
	}
	if _, ok := values["prompt"]; ok {
		t.Fatal("expected [mysql] group to be excluded when only [client] is requested")
	}
}

func TestParseOptionFileSocketAndQuotedValues(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "my.cnf")
	fixture := `[client]
user = 'openpanel'
password = "quoted-secret"
socket=/var/run/mysqld/mysqld.sock
database=panel
`
	os.WriteFile(path, []byte(fixture), 0600)

	values, err := parseOptionFile(path, "client")
	if err != nil {
		t.Fatal(err)
	}
	if values["user"] != "openpanel" {
		t.Fatalf("expected quotes stripped from user, got %q", values["user"])
	}
	if values["password"] != "quoted-secret" {
		t.Fatalf("expected quotes stripped from password, got %q", values["password"])
	}
	if values["socket"] != "/var/run/mysqld/mysqld.sock" {
		t.Fatalf("unexpected socket value: %q", values["socket"])
	}
}

func TestParseOptionFileMissingFile(t *testing.T) {
	if _, err := parseOptionFile("/nonexistent/my.cnf", "client"); err == nil {
		t.Fatal("expected error for missing option file")
	}
}

func TestOpenSurfacesOptionFileError(t *testing.T) {
	orig := OptionFilePath
	OptionFilePath = "/nonexistent/my.cnf"
	defer func() { OptionFilePath = orig }()

	if _, err := Open(); err == nil {
		t.Fatal("expected Open() to fail when the option file is missing")
	}
}
