// Package handlers implements listing, viewing, editing (see
// users_edit.go), suspending/unsuspending, creating, and deleting hosting
// accounts, plus private notes, a per-user custom message banner, live
// CPU/RAM/disk usage widgets and history, activity/login log viewing,
// per-user feature permission overrides, and per-container
// start/stop/restart/cpu/ram management (see users_containers.go) for the
// users list/detail pages.
package handlers

import (
	"bufio"
	"database/sql"
	"encoding/json"
	"fmt"
	"html/template"
	"math"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/gorilla/csrf"

	"openadmin/internal/admindb"
	"openadmin/internal/auth"
	"openadmin/internal/paneldb"
	"openadmin/internal/webtemplates"
)

// Users bundles the /users handlers.
type Users struct {
	MySQL    *sql.DB
	Sessions *auth.Manager
	AdminDB  *admindb.DB
}

// QuotaReportPath is the on-disk location of the generated quota report.
var QuotaReportPath = "/etc/openpanel/openpanel/quota_report.json"

type diskUsage struct {
	DiskUsed   interface{} `json:"disk_used"`
	DiskSoft   interface{} `json:"disk_soft"`
	DiskHard   interface{} `json:"disk_hard"`
	InodesUsed interface{} `json:"inodes_used"`
	InodesSoft interface{} `json:"inodes_soft"`
	InodesHard interface{} `json:"inodes_hard"`
}

// readDiskUsageAll reads the quota report generated by `opencli
// user-quota` (regenerating it is left to that existing cron/on-demand
// mechanism -- this just reads whatever is currently on disk). It does not
// itself shell out to regenerate a missing report, since triggering a
// system-wide quota scan as a side effect of a page load is a heavier
// behavior worth a deliberate follow-up decision rather than doing it
// silently here.
func readDiskUsageAll() map[string]diskUsage {
	out := map[string]diskUsage{}
	raw, err := os.ReadFile(QuotaReportPath)
	if err != nil {
		return out
	}
	var parsed struct {
		Users []struct {
			Username   string      `json:"username"`
			DiskUsed   interface{} `json:"disk_used"`
			DiskSoft   interface{} `json:"disk_soft"`
			DiskHard   interface{} `json:"disk_hard"`
			InodesUsed interface{} `json:"inodes_used"`
			InodesSoft interface{} `json:"inodes_soft"`
			InodesHard interface{} `json:"inodes_hard"`
		} `json:"users"`
	}
	if json.Unmarshal(raw, &parsed) != nil {
		return out
	}
	for _, u := range parsed.Users {
		if u.Username == "" {
			continue
		}
		out[u.Username] = diskUsage{
			DiskUsed: u.DiskUsed, DiskSoft: u.DiskSoft, DiskHard: u.DiskHard,
			InodesUsed: u.InodesUsed, InodesSoft: u.InodesSoft, InodesHard: u.InodesHard,
		}
	}
	return out
}

// toFloat coerces a disk-quota field (decoded from quota_report.json as
// float64/int/string) to a float64 so the usage-ratio math below can treat
// every field uniformly regardless of its JSON type.
func toFloat(v interface{}) float64 {
	switch t := v.(type) {
	case float64:
		return t
	case int64:
		return float64(t)
	case int:
		return float64(t)
	case string:
		f, _ := strconv.ParseFloat(t, 64)
		return f
	default:
		return 0
	}
}

// statFloat/statString walk a nested map[string]interface{} (a raw
// resource_usage.txt JSON line) along path, using forgiving
// `stat.memory.used.bytes`-style dotted access (missing keys read as zero
// value rather than erroring).
func statFloat(stat map[string]interface{}, path ...string) float64 {
	var cur interface{} = stat
	for _, p := range path {
		m, ok := cur.(map[string]interface{})
		if !ok {
			return 0
		}
		cur = m[p]
	}
	return toFloat(cur)
}

func statString(stat map[string]interface{}, path ...string) string {
	var cur interface{} = stat
	for _, p := range path {
		m, ok := cur.(map[string]interface{})
		if !ok {
			return ""
		}
		cur = m[p]
	}
	s, _ := cur.(string)
	return s
}

// arcCircumference is the SVG progress-ring circumference used throughout
// all.html's mini usage donuts (r=12.5 -> 2*pi*12.5).
const arcCircumference = 78.53981633974483

func arcOffset(percent float64) string {
	return strconv.FormatFloat(arcCircumference*(1-percent/100), 'f', -1, 64)
}

// usageColorClass is the shared red/orange/green/blue/gray threshold
// ladder (>=90/>=80/>=60/>0) used by the usage rings.
func usageColorClass(pct float64) string {
	switch {
	case pct >= 90:
		return "red"
	case pct >= 80:
		return "orange"
	case pct >= 60:
		return "green"
	case pct > 0:
		return "blue"
	default:
		return "gray"
	}
}

// usageWidgetData is the precomputed set of numbers/labels the per-user
// mem/cpu/disk/inodes usage rings need -- built here in Go rather than in
// the template since html/template has no arithmetic operators.
type usageWidgetData struct {
	MemPercent  int
	MemOffset   string
	MemColor    string
	MemTooltip  string
	CPUPercent  int
	CPUOffset   string
	CPUColor    string
	CPUTooltip  string
	HasDiskData bool
	DiskPercent int
	DiskOffset  string
	DiskColor   string
	DiskTooltip string

	InodesPercent int
	InodesOffset  string
	InodesColor   string
	InodesTooltip string
}

// buildUsageWidget computes the Memory/CPU/Disk/Inodes ring math for the
// users list page, including a preserved quirk: a real red/orange/green/
// blue color class is computed for the Memory ring and then immediately
// overridden back to a hardcoded 'gray', so the Memory ring is always gray
// regardless of usage -- the CPU/Disk/Inodes rings don't have this
// override and do color dynamically.
func buildUsageWidget(suspended bool, stat map[string]interface{}, disk diskUsage, hasDisk bool) usageWidgetData {
	memUsedHuman, memTotalHuman := "0 B", "0 B"
	memPct, cpuPct := 0.0, 0.0
	if !suspended && stat != nil {
		memUsedHuman = statString(stat, "memory", "used", "human")
		memTotalHuman = statString(stat, "memory", "total", "human")
		if statFloat(stat, "memory", "total", "bytes") != 0 {
			memPct = statFloat(stat, "memory", "usage_pct")
		}
		cpuPct = statFloat(stat, "cpu", "usage", "pct")
	}

	w := usageWidgetData{
		MemPercent: int(math.Round(memPct)),
		MemOffset:  arcOffset(memPct),
		MemColor:   "gray",
		MemTooltip: fmt.Sprintf("Memory usage: %s / %s", memUsedHuman, memTotalHuman),
		CPUPercent: int(math.Round(cpuPct)),
		CPUOffset:  arcOffset(cpuPct),
		CPUColor:   usageColorClass(cpuPct),
		CPUTooltip: fmt.Sprintf("CPU usage: %v%%", cpuPct),
	}

	if hasDisk {
		diskHard, diskUsed := toFloat(disk.DiskHard), toFloat(disk.DiskUsed)
		diskPct := 0.0
		if diskHard != 0 {
			diskPct = diskUsed / diskHard * 100
		}
		inodesHard, inodesUsed := toFloat(disk.InodesHard), toFloat(disk.InodesUsed)
		inodesPct := 0.0
		if inodesHard != 0 {
			inodesPct = inodesUsed / inodesHard * 100
		}
		inodesOffsetPct := inodesPct
		if inodesOffsetPct > 100 {
			inodesOffsetPct = 100
		}

		w.HasDiskData = true
		w.DiskPercent = int(math.Round(diskPct))
		w.DiskOffset = arcOffset(diskPct)
		w.DiskColor = usageColorClass(diskPct)
		w.DiskTooltip = fmt.Sprintf("Disk usage: %s / %s", humanGB(diskUsed), humanBytesOrInf(diskHard))
		w.InodesPercent = int(math.Round(inodesPct))
		w.InodesOffset = arcOffset(inodesOffsetPct)
		w.InodesColor = usageColorClass(inodesPct)
		w.InodesTooltip = fmt.Sprintf("Inodes usage: %s / %s", humanCount(inodesUsed), humanCountOrInf(inodesHard))
	}

	return w
}

// detailStatsWidget is the precomputed ring data for the user detail page's
// Statistics tab -- a larger set of rings (radius 29, not the list page's
// 12.5) with its own color thresholds, so it's kept separate from
// usageWidgetData rather than shared.
type detailStatsWidget struct {
	DiskUsageRounded string
	DiskOffset       string
	DiskColorClass   string
	DiskUsedHuman    string
	DiskHardHuman    string

	InodesUsageRounded string
	InodesOffset       string
	InodesColorClass   string
	InodesUsedHuman    string
	InodesHardHuman    string

	CPURatioRounded string
	CPUOffset       string
	CPUColor        string
	CPUHumanUsage   string
	CPUHumanTotal   string

	RAMPercentRounded string
	RAMOffset         string
	RAMColor          string
	RAMHumanUsage     string
	RAMHumanTotal     string
}

const detailRingCircumference = 182.212373908208

func detailRingColorClass(pct float64) string {
	switch {
	case pct > 90:
		return "stroke-red-200 dark:stroke-red-500/40"
	case pct > 80:
		return "stroke-orange-200 dark:stroke-orange-500/40"
	case pct > 60:
		return "stroke-blue-200 dark:stroke-blue-500/40"
	default:
		return "stroke-gray-200 dark:stroke-gray-500/40"
	}
}

func detailRingOffset(pctClamped float64) string {
	return strconv.FormatFloat(detailRingCircumference-(detailRingCircumference*pctClamped/100), 'f', -1, 64)
}

func round2(f float64) float64 {
	return math.Round(f*100) / 100
}

func humanBytesOrInf(hard float64) string {
	if hard == 0 {
		return "∞"
	}
	return humanGB(hard)
}

func humanGB(v float64) string {
	return strconv.FormatFloat(round2(v/1024000), 'f', -1, 64) + "GB"
}

func humanCount(v float64) string {
	if v == 0 {
		return "0"
	}
	if v >= 1000000 {
		return strconv.FormatFloat(round2(v/1000000), 'f', -1, 64) + "M"
	}
	return strconv.FormatFloat(v, 'f', -1, 64)
}

func humanCountOrInf(v float64) string {
	if v == 0 {
		return "∞"
	}
	return humanCount(v)
}

func buildDetailStatsWidget(suspended bool, disk diskUsage, stats map[string]interface{}) detailStatsWidget {
	diskUsed, diskHard := toFloat(disk.DiskUsed), toFloat(disk.DiskHard)
	diskPct := 0.0
	if diskHard != 0 {
		diskPct = diskUsed / diskHard * 100
	}
	diskClamped := diskPct
	if diskClamped > 100 {
		diskClamped = 100
	}

	inodesUsed, inodesHard := toFloat(disk.InodesUsed), toFloat(disk.InodesHard)
	inodesPct := 0.0
	if diskHard != 0 {
		inodesPct = inodesUsed / diskHard * 100
	}
	inodesClamped := inodesPct
	if inodesClamped > 100 {
		inodesClamped = 100
	}

	percentCPU, totalCPU, percentMem := 0.0, 100.0, 0.0
	humanCPUUsage, humanCPUTotal := "0 cores", "0 cores"
	humanMemUsage, humanMemTotal := "0B", "0B"
	if !suspended && stats != nil {
		percentCPU = statFloat(stats, "cpu", "usage", "pct")
		if t := statFloat(stats, "cpu", "total", "pct"); t != 0 {
			totalCPU = t
		}
		humanCPUUsage = statString(stats, "cpu", "usage", "human")
		humanCPUTotal = statString(stats, "cpu", "total", "human")
		percentMem = statFloat(stats, "memory", "usage_pct")
		humanMemUsage = statString(stats, "memory", "used", "human")
		humanMemTotal = statString(stats, "memory", "total", "human")
	}
	ratioCPU := percentCPU / totalCPU * 100

	diskUsedHuman := "0B"
	if diskUsed != 0 {
		diskUsedHuman = strconv.FormatFloat(round2(diskUsed/1024000), 'f', -1, 64) + "GB"
	}

	return detailStatsWidget{
		DiskUsageRounded: strconv.FormatFloat(round2(diskClamped), 'f', -1, 64),
		DiskOffset:       detailRingOffset(round2(diskClamped)),
		DiskColorClass:   detailRingColorClass(diskPct),
		DiskUsedHuman:    diskUsedHuman,
		DiskHardHuman:    humanBytesOrInf(diskHard),

		InodesUsageRounded: strconv.FormatFloat(round2(inodesClamped), 'f', -1, 64),
		InodesOffset:       detailRingOffset(round2(inodesClamped)),
		InodesColorClass:   detailRingColorClass(inodesPct),
		InodesUsedHuman:    humanCount(inodesUsed),
		InodesHardHuman:    humanCountOrInf(inodesHard),

		CPURatioRounded: strconv.FormatFloat(round2(ratioCPU), 'f', -1, 64),
		CPUOffset:       detailRingOffset(ratioCPU),
		CPUColor:        usageColorClass(percentCPU),
		CPUHumanUsage:   humanCPUUsage,
		CPUHumanTotal:   humanCPUTotal,

		RAMPercentRounded: strconv.FormatFloat(round2(percentMem), 'f', -1, 64),
		RAMOffset:         detailRingOffset(percentMem),
		RAMColor:          usageColorClass(percentMem),
		RAMHumanUsage:     humanMemUsage,
		RAMHumanTotal:     humanMemTotal,
	}
}

func stripSuspendedPrefix(username string) string {
	if idx := strings.LastIndex(username, "_"); strings.Contains(username, "SUSPENDED_") && idx != -1 {
		return username[idx+1:]
	}
	return username
}

func readDiskUsageFor(username string) (diskUsage, bool) {
	all := readDiskUsageAll()
	d, ok := all[stripSuspendedPrefix(username)]
	return d, ok
}

// readUsageStatsFor reads the last JSON line of a single user's
// resource_usage.txt.
func readUsageStatsFor(context string) (json.RawMessage, bool) {
	raw, err := os.ReadFile("/home/" + context + "/resource_usage.txt")
	if err != nil {
		return nil, false
	}
	lines := strings.Split(strings.TrimRight(string(raw), "\n"), "\n")
	if len(lines) == 0 || lines[len(lines)-1] == "" {
		return nil, false
	}
	last := lines[len(lines)-1]
	if !json.Valid([]byte(last)) {
		return nil, false
	}
	return json.RawMessage(last), true
}

// readUsageStatsAll reads the last JSON line of every
// /home/*/resource_usage.txt, keyed by each entry's own "user" field --
// done here in Go rather than in the template, since html/template has no
// filter for this kind of lookup.
func readUsageStatsAll() map[string]map[string]interface{} {
	out := map[string]map[string]interface{}{}
	entries, err := os.ReadDir("/home")
	if err != nil {
		return out
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		raw, err := os.ReadFile(filepath.Join("/home", e.Name(), "resource_usage.txt"))
		if err != nil {
			continue
		}
		lines := strings.Split(strings.TrimRight(string(raw), "\n"), "\n")
		if len(lines) == 0 || lines[len(lines)-1] == "" {
			continue
		}
		var parsed map[string]interface{}
		if json.Unmarshal([]byte(lines[len(lines)-1]), &parsed) != nil {
			continue
		}
		if user, ok := parsed["user"].(string); ok && user != "" {
			out[user] = parsed
		}
	}
	return out
}

// readUserNotes returns the raw contents of /home/{context}/notes.txt, or
// "" if missing/unreadable.
func readUserNotes(context string) string {
	raw, err := os.ReadFile("/home/" + context + "/notes.txt")
	if err != nil {
		return ""
	}
	return string(raw)
}

// userFeaturesPath is where a user's custom feature-permission overrides are
// stored, one enabled feature name per line -- mirroring notes.txt. Its
// presence means the user has left their plan's feature-set defaults and
// switched to a custom, per-user list.
func userFeaturesPath(context string) string {
	return "/home/" + context + "/features.txt"
}

// notesMapFor builds a map of each user's private note, keyed by each
// user's "server"/context column.
func notesMapFor(users []paneldb.RowMap) map[string]string {
	out := map[string]string{}
	for _, u := range users {
		context, _ := u["server"].(string)
		if context == "" {
			continue
		}
		out[context] = readUserNotes(context)
	}
	return out
}

func (u *Users) resellerScope(r *http.Request) string {
	currentUser := auth.CurrentUser(r)
	if currentUser.Role == "reseller" {
		return currentUser.Username
	}
	return ""
}

type usersListPageData struct {
	webtemplates.Chrome
	Users         []paneldb.RowMap
	Plans         []paneldb.RowMap
	MySQLIsDown   bool
	Widgets       map[string]usageWidgetData
	Notes         map[string]string
	SortCol       string
	SortDirection string
	CSRFToken     string
	Flashes       []auth.Flash
}

// ServeList handles GET /users, /users/.
func (u *Users) ServeList(w http.ResponseWriter, r *http.Request) {
	resellerOwner := u.resellerScope(r)

	users, err := paneldb.GetAllUsers(u.MySQL, resellerOwner)
	mysqlIsDown := err != nil

	var plans []paneldb.RowMap
	sortCol := r.URL.Query().Get("sort")
	direction := r.URL.Query().Get("direction")
	if !mysqlIsDown {
		var allowed []int
		if resellerOwner != "" {
			ids, ok := paneldb.AllowedPlansForReseller(resellerOwner)
			if ok {
				allowed = ids
			}
		}
		plans, _ = paneldb.GetAllPlans(u.MySQL, allowed)

		if sortCol != "" {
			sortRowMaps(users, sortCol, strings.EqualFold(direction, "desc"))
		}
	}

	if r.URL.Query().Get("output") == "json" {
		writeJSON(w, map[string]interface{}{
			"users": users,
			"stats": readUsageStatsAll(),
			"disk":  readDiskUsageAll(),
		})
		return
	}

	statsAll := readUsageStatsAll()
	diskAll := readDiskUsageAll()
	widgets := make(map[string]usageWidgetData, len(users))
	for _, row := range users {
		uname, _ := row["username"].(string)
		if uname == "" {
			continue
		}
		plain := stripSuspendedPrefix(uname)
		d, hasDisk := diskAll[plain]
		widgets[uname] = buildUsageWidget(strings.Contains(uname, "SUSPENDED_"), statsAll[plain], d, hasDisk)
	}

	webtemplates.Render(w, "users_list.html", usersListPageData{
		Chrome:        buildChrome(r, "Users"),
		Users:         users,
		Plans:         plans,
		MySQLIsDown:   mysqlIsDown,
		Widgets:       widgets,
		Notes:         notesMapFor(users),
		SortCol:       sortCol,
		SortDirection: direction,
		CSRFToken:     csrf.Token(r),
		Flashes:       auth.PopFlashes(w, r, u.Sessions),
	})
}

type userDetailPageData struct {
	webtemplates.Chrome
	Username          string
	User              *paneldb.UserData
	Disk              diskUsage
	Notes             string
	Stats             map[string]interface{}
	StatsWidget       detailStatsWidget
	ServerIP          string
	ServerName        string
	DockerCtx         string
	IPType            string
	Locale            string
	CountryCode       string
	EnvData           map[string]string
	PlanCPU           string
	PlanRAM           string
	Services          []composeServiceView
	Features          []map[string]interface{}
	HasCustomFeatures bool
	CSRFToken         string
	Flashes           []auth.Flash
}

var ipv4Re = regexp.MustCompile(`^\d+\.\d+\.\d+\.\d+$`)
var ipv6Re = regexp.MustCompile(`^[0-9a-fA-F:]+$`)

func ipTypeOf(ip string) string {
	switch {
	case ipv4Re.MatchString(ip):
		return "IPv4"
	case ip != "" && ipv6Re.MatchString(ip):
		return "IPv6"
	default:
		return "Invalid"
	}
}

func firstIPFor(username string) string {
	raw, err := os.ReadFile("/etc/openpanel/openpanel/core/users/" + username + "/ip.json")
	if err != nil {
		return ""
	}
	var data map[string]interface{}
	if json.Unmarshal(raw, &data) != nil {
		return ""
	}
	if ips, ok := data["ip_addresses"].([]interface{}); ok && len(ips) > 0 {
		if s, ok := ips[0].(string); ok {
			return s
		}
	}
	if ip, ok := data["ip"].(string); ok {
		return ip
	}
	return ""
}

func userLocale(context string) string {
	raw, err := os.ReadFile("/home/" + context + "/locale")
	if err != nil {
		return ""
	}
	code := strings.ToLower(strings.TrimSpace(string(raw)))
	if len(code) == 2 {
		for _, c := range code {
			if c < 'a' || c > 'z' {
				return ""
			}
		}
		return code
	}
	return ""
}

func readEnvFile(context string) map[string]string {
	out := map[string]string{}
	raw, err := os.ReadFile("/home/" + context + "/.env")
	if err != nil {
		return out
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		out[strings.TrimSpace(key)] = strings.Trim(strings.TrimSpace(value), `"`)
	}
	return out
}

var countryLookupClient = &http.Client{Timeout: 2 * time.Second}

func countryCodeForIP(ip string) string {
	if ip == "" {
		return ""
	}
	resp, err := countryLookupClient.Get("https://api.country.is/" + ip)
	if err != nil {
		return ""
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return ""
	}
	var data struct {
		Country string `json:"country"`
	}
	if json.NewDecoder(resp.Body).Decode(&data) != nil {
		return ""
	}
	return data.Country
}

// ServeDetail handles GET /users/{username}.
func (u *Users) ServeDetail(w http.ResponseWriter, r *http.Request) {
	username := r.PathValue("username")
	currentUser := auth.CurrentUser(r)

	if !paneldb.CheckIfOwnerForUser(u.MySQL, username, currentUser.Username, currentUser.Role) {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return
	}

	userData, err := paneldb.GetUserDataByUsername(u.MySQL, username)
	if err != nil {
		if r.URL.Query().Get("output") == "json" {
			writeJSON(w, map[string]string{"message": "Error: User " + username + " not found", "status": "error"})
			return
		}
		auth.AddFlash(w, r, u.Sessions, "Error: User "+username+" not found", "error")
		http.Redirect(w, r, "/users", http.StatusSeeOther)
		return
	}

	disk, _ := readDiskUsageFor(username)
	stats, hasStats := readUsageStatsFor(userData.Context)
	serverIP := firstIPFor(username)
	if serverIP == "" || ipTypeOf(serverIP) == "Invalid" {
		serverIP = chromeSite.PublicIP
	}
	envData := readEnvFile(userData.Context)

	if r.URL.Query().Get("output") == "json" {
		resp := map[string]interface{}{
			"username":       username,
			"user":           userData,
			"disk":           disk,
			"server_ip":      serverIP,
			"server_name":    serverName(),
			"docker_context": userData.Context,
			"env_data":       envData,
			"ip_type":        ipTypeOf(serverIP),
			"locale":         userLocale(userData.Context),
			"country_code":   countryCodeForIP(serverIP),
		}
		if hasStats {
			resp["stats"] = stats
		} else {
			resp["stats"] = "no data yet"
		}
		writeJSON(w, resp)
		return
	}

	var parsedStats map[string]interface{}
	if hasStats {
		_ = json.Unmarshal(stats, &parsedStats)
	}

	featureSet := "default"
	var planCPU, planRAM string
	if planRow, err := paneldb.GetPlanByID(u.MySQL, strconv.FormatInt(userData.PlanID, 10)); err == nil {
		if fs, ok := planRow["feature_set"].(string); ok && fs != "" {
			featureSet = fs
		}
		planCPU, _ = planRow["cpu"].(string)
		planRAM, _ = planRow["ram"].(string)
	}
	featuresPath := FeatureSetPathForPlan(featureSet, userData.Owner.String)
	hasCustomFeatures := false
	if _, err := os.Stat(userFeaturesPath(userData.Context)); err == nil {
		hasCustomFeatures = true
		featuresPath = userFeaturesPath(userData.Context)
	}
	features, _ := FeaturesForSet(featuresPath)

	webtemplates.Render(w, "user_detail.html", userDetailPageData{
		Chrome:            buildChrome(r, "User: "+stripSuspendedPrefix(username)),
		Username:          username,
		User:              userData,
		Disk:              disk,
		Notes:             readUserNotes(userData.Context),
		Stats:             parsedStats,
		StatsWidget:       buildDetailStatsWidget(strings.Contains(username, "SUSPENDED_"), disk, parsedStats),
		ServerIP:          serverIP,
		ServerName:        serverName(),
		DockerCtx:         userData.Context,
		IPType:            ipTypeOf(serverIP),
		Locale:            userLocale(userData.Context),
		CountryCode:       countryCodeForIP(serverIP),
		EnvData:           envData,
		PlanCPU:           planCPU,
		PlanRAM:           planRAM,
		Services:          composeServicesForUser(u.MySQL, username),
		Features:          features,
		HasCustomFeatures: hasCustomFeatures,
		CSRFToken:         csrf.Token(r),
		Flashes:           auth.PopFlashes(w, r, u.Sessions),
	})
}

func serverName() string {
	name, err := os.Hostname()
	if err != nil {
		return ""
	}
	return name
}

// HandleNotes handles GET/POST /get_user_notes/{username}: GET returns the
// saved private note for the user, POST overwrites it.
func (u *Users) HandleNotes(w http.ResponseWriter, r *http.Request) {
	username := r.PathValue("username")
	currentUser := auth.CurrentUser(r)

	if !paneldb.CheckIfOwnerForUser(u.MySQL, username, currentUser.Username, currentUser.Role) {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return
	}

	userData, err := paneldb.GetUserDataByUsername(u.MySQL, username)
	if err != nil {
		writeJSONError(w, http.StatusNotFound, "User not found")
		return
	}

	if r.Method == http.MethodPost {
		var body struct {
			Notes string `json:"notes"`
		}
		if json.NewDecoder(r.Body).Decode(&body) != nil {
			writeJSONError(w, http.StatusBadRequest, "Invalid content type. Expected JSON.")
			return
		}
		if err := os.WriteFile("/home/"+userData.Context+"/notes.txt", []byte(body.Notes), 0644); err != nil {
			writeJSONError(w, http.StatusInternalServerError, "Failed to save notes")
			return
		}
		writeJSON(w, map[string]string{"message": "Notes for user " + username + " saved successfully."})
		return
	}

	writeJSON(w, map[string]string{"notes": readUserNotes(userData.Context)})
}

// ServeIPs handles GET /json/ips: a map of usernames with a dedicated IP
// address on file to that address.
func (u *Users) ServeIPs(w http.ResponseWriter, r *http.Request) {
	out := map[string]interface{}{}
	matches, _ := filepath.Glob("/etc/openpanel/openpanel/core/users/*/ip.json")
	for _, ipFile := range matches {
		username := filepath.Base(filepath.Dir(ipFile))
		raw, err := os.ReadFile(ipFile)
		if err != nil {
			continue
		}
		var parsed struct {
			IP string `json:"ip"`
		}
		if json.Unmarshal(raw, &parsed) != nil {
			continue
		}
		out[username] = parsed.IP
	}
	writeJSON(w, out)
}

// HandleManage handles POST /user/{action}/{username} for the
// suspend/unsuspend/delete/permissions actions. ('edit' is not yet
// implemented -- see the package doc comment.)
func (u *Users) HandleManage(w http.ResponseWriter, r *http.Request) {
	action := r.PathValue("action")
	username := r.PathValue("username")
	currentUser := auth.CurrentUser(r)

	if !paneldb.CheckIfOwnerForUser(u.MySQL, username, currentUser.Username, currentUser.Role) {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return
	}

	switch action {
	case "suspend":
		success, output := runOpenCLI("", "opencli", "user-suspend", username, "-y")
		if success && strings.Contains(output, "successfully") {
			logUserAction(username, clientIP(r), "Administrator "+currentUser.Username+" suspended user "+username)
			auth.AddFlash(w, r, u.Sessions, "User '"+username+"' suspended successfully", "info")
		} else {
			auth.AddFlash(w, r, u.Sessions, "Error suspending user "+username, "error")
		}

	case "unsuspend":
		// Unlike every other call site in this module (which only strips
		// when "SUSPENDED_" is actually present), this branch strips
		// everything up to the LAST underscore unconditionally whenever one
		// exists at all. If a username itself contains an underscore, this
		// would truncate it incorrectly; preserved as-is rather than
		// silently changed, since opencli's own username validation is the
		// actual source of truth for what usernames can contain, not this
		// handler.
		plain := username
		if idx := strings.LastIndex(username, "_"); idx != -1 {
			plain = username[idx+1:]
		}
		success, output := runOpenCLI("", "opencli", "user-unsuspend", plain)
		if success && strings.Contains(output, "success") {
			logUserAction(plain, clientIP(r), "Administrator "+currentUser.Username+" unsuspended user "+plain)
			auth.AddFlash(w, r, u.Sessions, "User '"+plain+"' unsuspended successfully", "info")
		} else {
			auth.AddFlash(w, r, u.Sessions, "Error unsuspending user "+plain, "error")
		}

	case "delete":
		if r.FormValue("confirmation") != username {
			http.Error(w, "Bad Request", http.StatusBadRequest)
			return
		}
		success, _ := runOpenCLI("", "opencli", "user-delete", username, "-y")
		if success {
			auth.AddFlash(w, r, u.Sessions, "User '"+username+"' deleted successfully", "info")
		} else {
			auth.AddFlash(w, r, u.Sessions, "Error deleting user "+username, "error")
			http.Redirect(w, r, "/users", http.StatusSeeOther)
			return
		}

	case "edit":
		u.handleEditUser(w, r, username, currentUser)
		return

	case "permissions":
		if err := r.ParseForm(); err != nil {
			http.Error(w, "Bad Request", http.StatusBadRequest)
			return
		}
		userData, err := paneldb.GetUserDataByUsername(u.MySQL, username)
		if err != nil {
			auth.AddFlash(w, r, u.Sessions, "Error: User "+username+" not found", "error")
			http.Redirect(w, r, "/users", http.StatusSeeOther)
			return
		}
		keys := make([]string, 0, len(r.PostForm))
		for k := range r.PostForm {
			if k == "csrf_token" {
				continue
			}
			keys = append(keys, k)
		}
		sort.Strings(keys)
		var b strings.Builder
		for _, k := range keys {
			b.WriteString(k + "\n")
		}
		if err := os.WriteFile(userFeaturesPath(userData.Context), []byte(b.String()), 0644); err != nil {
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
			return
		}
		logUserAction(username, clientIP(r), "Administrator "+currentUser.Username+" updated permissions for user "+username)
		auth.AddFlash(w, r, u.Sessions, "Permissions for '"+username+"' updated successfully", "success")
		http.Redirect(w, r, "/users/"+username+"#permissions", http.StatusSeeOther)
		return

	case "permissions_reset":
		userData, err := paneldb.GetUserDataByUsername(u.MySQL, username)
		if err != nil {
			auth.AddFlash(w, r, u.Sessions, "Error: User "+username+" not found", "error")
			http.Redirect(w, r, "/users", http.StatusSeeOther)
			return
		}
		if err := os.Remove(userFeaturesPath(userData.Context)); err != nil && !os.IsNotExist(err) {
			http.Error(w, "Internal Server Error", http.StatusInternalServerError)
			return
		}
		logUserAction(username, clientIP(r), "Administrator "+currentUser.Username+" reset permissions for user "+username+" to plan defaults")
		auth.AddFlash(w, r, u.Sessions, "Permissions for '"+username+"' reset to plan defaults", "success")
		http.Redirect(w, r, "/users/"+username+"#permissions", http.StatusSeeOther)
		return

	default:
		auth.AddFlash(w, r, u.Sessions, "Invalid user action, valid options are: edit, suspend, unsuspend, delete, permissions, permissions_reset", "error")
	}

	http.Redirect(w, r, "/users", http.StatusSeeOther)
}

type userCreatePageData struct {
	webtemplates.Chrome
	Plans            []paneldb.RowMap
	MySQLIsDown      bool
	WebServer        string
	MySQLType        string
	VarnishEnabled   bool
	Webservers       []userCreateOption
	SQLOptions       []userCreateOption
	ResellersEnabled bool
	CSRFToken        string
	Flashes          []auth.Flash
}

type userCreateOption struct {
	Value       string
	Label       string
	Description string
	Icon        template.HTML
}

// userCreateWebservers/userCreateSQLOptions are the small hardcoded option
// lists shown on the add-user form.
var userCreateWebservers = []userCreateOption{
	{Value: "apache", Label: "Apache", Description: "Battle-tested and broadly compatible, with full .htaccess support.",
		Icon: `<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="w-10 h-10" aria-label="Apache"><title>Apache</title><path fill="#D22128" d="M17.805 2.197v.066h.156v.44h.072v-.44h.156v-.066zm.9 0l-.175.353-.172-.353h-.087v.506h.067V2.3l.172.35h.045l.172-.35v.404h.066v-.506zm-4.257 1c-.204.31-.424.66-.66 1.06l-.04.062a44.457 44.457 0 00-1.265 2.29c-.187.36-.38.742-.577 1.146l2.267-.25c.66-.302.955-.578 1.242-.976a15.5 15.5 0 00.23-.342c.23-.363.46-.763.663-1.16.197-.386.37-.767.505-1.11.083-.22.15-.422.198-.6.042-.158.074-.307.1-.45-.884.15-1.965.295-2.668.33zM11.894 7.78l-.077.16c-.078.16-.157.32-.236.488-.086.18-.172.364-.26.552l-.132.287a75.265 75.265 0 00-1.427 3.3c-.163.397-.327.807-.493 1.23-.15.38-.297.765-.45 1.164l-.02.06c-.15.396-.3.802-.453 1.22l-.01.027.72-.08a.213.213 0 01-.042-.006c.863-.106 2.01-.75 2.75-1.547.342-.367.652-.8.94-1.306.213-.377.413-.795.604-1.258.168-.405.328-.843.48-1.318-.196.105-.423.18-.673.235a2.184 2.184 0 01-.273.046c.806-.31 1.314-.905 1.683-1.64a2.816 2.816 0 01-.968.428c-.06.012-.116.022-.174.03l-.043.006h.002c.278-.118.514-.248.718-.403a2.571 2.571 0 00.637-.698l.063-.104.077-.154a8.107 8.107 0 00.367-.85l.03-.088a3.04 3.04 0 00.123-.463.733.733 0 01-.094.065c-.243.145-.66.277-.996.34l.663-.074-.664.073h-.017l-.1.017c.006-.003.01-.006.017-.008l-2.265.25-.013.022zM8.27 16.45c-.117.323-.236.654-.355.992l-.005.015c-.016.046-.032.094-.05.142-.08.227-.15.432-.31.9.264.12.475.435.675.793a1.44 1.44 0 00-.466-.99c1.293.06 2.41-.27 2.99-1.217.05-.084.096-.173.14-.268-.26.333-.59.474-1.2.44 0 0-.004 0-.005.002l.004-.002c.9-.404 1.354-.79 1.754-1.433.094-.153.186-.32.28-.503-.788.81-1.702 1.04-2.664.865l-.72.078a6.43 6.43 0 00-.067.183zM15.42.112c-.376.222-1 .85-1.748 1.763l.686 1.294c.48-.687.97-1.307 1.462-1.836l.058-.062c-.02.02-.04.04-.057.062-.16.176-.644.74-1.375 1.863.703-.035 1.784-.18 2.666-.33.262-1.47-.258-2.142-.258-2.142s-.66-1.07-1.436-.61zm-3.084 6.402a40.253 40.253 0 011.306-2.26l.04-.064c.224-.352.45-.693.677-1.02l-.685-1.293-.157.192c-.197.245-.403.51-.613.79a39.853 39.853 0 00-2.016 2.97l-.022.038.893 1.763c.19-.378.38-.752.575-1.118zm-3.73 8.32c.158-.406.319-.81.483-1.225.156-.394.32-.79.484-1.19a91.133 91.133 0 011.6-3.604l.205-.424c.12-.243.237-.485.36-.724a.125.125 0 01.02-.04l-.895-1.763-.044.07c-.207.34-.414.687-.617 1.042a38.056 38.056 0 00-1.092 2.04l-.094.193a24.573 24.573 0 00-1.258 3.087 18.492 18.492 0 00-.52 1.997l.896 1.77c.117-.317.24-.638.364-.963zm-1.376-.476a13.38 13.38 0 00-.234 1.692c0 .02-.004.04-.005.06-.28-.45-1.03-.888-1.026-.884.537.778.944 1.55 1.005 2.31-.29.058-.684-.027-1.14-.195.475.436.83.556.97.588-.434.03-.89.328-1.346.67.668-.27 1.21-.38 1.596-.29-.61 1.74-1.23 3.655-1.843 5.69a.538.538 0 00.364-.354c.11-.368.84-2.786 1.978-5.965l.097-.27.028-.078c.12-.332.246-.672.374-1.02l.09-.237v-.004L7.24 14.3c-.003.02-.01.04-.012.06z"/></svg>`},
	{Value: "nginx", Label: "Nginx", Description: "Lightweight and fast, ideal for high traffic and serving static content.",
		Icon: `<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="w-10 h-10" aria-label="NGINX"><title>NGINX</title><path fill="#009639" d="M12 0L1.605 6v12L12 24l10.395-6V6L12 0zm6 16.59c0 .705-.646 1.29-1.529 1.29-.631 0-1.351-.255-1.801-.81l-6-7.141v6.66c0 .721-.57 1.29-1.274 1.29H7.32c-.721 0-1.29-.6-1.29-1.29V7.41c0-.705.63-1.29 1.5-1.29.646 0 1.38.255 1.83.81l5.97 7.141V7.41c0-.721.6-1.29 1.29-1.29h.075c.72 0 1.29.6 1.29 1.29v9.18H18z"/></svg>`},
	{Value: "openresty", Label: "OpenResty", Description: "Nginx core extended with Lua scripting for advanced routing and logic.",
		Icon: `<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="w-10 h-10" aria-label="OpenResty"><title>OpenResty</title><path fill="#7DC242" d="M12 0L1.75 6v12L12 24l10.25-6V6zm-1.775 18l1.08-4.657-2.428-2.397L13.79 6l-1.082 4.665 2.414 2.384z"/></svg>`},
	{Value: "openlitespeed", Label: "OpenLitespeed", Description: "High-performance server with built-in caching and LSAPI for PHP.",
		Icon: `<svg role="img" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" enable-background="new 50 50 200 200" xml:space="preserve" class="w-10 h-10" id="Layer_1" viewBox="50 50 200 200" width="50" height="50">
<g>
	<path fill="#75D1DF" d="M216.455,101.332c-0.242-0.327-0.615-0.529-1.014-0.561c-0.401-0.033-0.795,0.116-1.086,0.399l-6.555,6.532
		c-0.479,0.479-0.537,1.236-0.152,1.787c8.453,11.95,12.933,25.954,12.933,40.514c0,38.906-31.709,70.57-70.685,70.57
		c-2.703,0-5.517-0.197-8.838-0.609c-0.206-0.03-1.092-0.166-1.649-0.256c-2.781-0.427-5.348-0.959-7.844-1.623
		c0,0-0.395-0.1-0.479-0.129c-0.027-0.004-0.046-0.012-0.072-0.023c-3.154-0.887-6.227-1.982-9.145-3.262
		c-2.914-1.259-5.838-2.795-8.712-4.581l85.846-45.399c2.728-1.443,4.389-3.986,4.438-6.801c0.057-2.811-1.5-5.418-4.176-6.967
		l-29.482-17.062l43.625-43.626c3.137-3.13,2.887-5.947,2.133-7.744c-0.902-2.221-3.245-3.773-5.693-3.773
		c-1.316,0-2.539,0.353-4.086,1.182l-104.732,55.384c-2.741,1.443-4.407,3.994-4.458,6.833c-0.041,2.823,1.538,5.419,4.217,6.943
		l29.535,16.993l-31.919,31.91c-1.776-1.925-3.457-3.938-5.002-6.019c-6.52-8.793-10.806-18.51-12.732-28.875
		c-0.029-0.147-0.054-0.299-0.07-0.447c-0.006-0.028-0.008-0.057-0.015-0.094l-0.043-0.215c-0.29-1.707-0.608-3.693-0.796-5.672
		c-0.044-0.459-0.059-0.948-0.068-1.412c0-0.012,0-0.02-0.006-0.032l-0.102-1.796c-0.069-1.014-0.144-2.162-0.144-3.332
		c0-4.821,0.479-9.611,1.432-14.232c0.447-2.164,0.993-4.297,1.632-6.339c0.024-0.071,0.039-0.126,0.052-0.2
		c0.007-0.038,0.017-0.11,0.033-0.16c0,0,0-0.004,0.001-0.007c9.233-29.73,36.332-49.706,67.431-49.706
		c4.276,0,8.663,0.495,13.805,1.562l0.624,0.132c1.611,0.338,3.408,0.802,5.48,1.408c1.102,0.321,2.205,0.719,3.178,1.067
		l0.918,0.329c0.842,0.291,1.727,0.598,2.527,0.931c0.012,0.003,0.023,0.013,0.041,0.016c0.114,0.045,0.213,0.092,0.332,0.144
		l0.045,0.023c0.39,0.181,0.845,0.169,1.228-0.037l10.327-5.467c0.451-0.237,0.733-0.709,0.738-1.226c0-0.513-0.287-0.98-0.738-1.22
		c-11.828-6.282-25.147-9.6-38.504-9.6c-45.502,0-82.516,37.012-82.516,82.515c0,18.435,6.054,35.94,17.509,50.62
		c1.512,1.936,3.18,3.868,4.968,5.775l-3.366,3.37c-3.122,3.102-2.892,5.911-2.145,7.72c0.924,2.229,3.273,3.785,5.714,3.785
		c1.29,0,2.545-0.361,4.071-1.17l7.001-3.715c2.307,1.697,4.635,3.244,6.929,4.602c12.75,7.535,27.214,11.521,41.835,11.521
		c45.488,0,82.5-37.014,82.5-82.511C232.508,132.412,226.963,115.582,216.455,101.332z"></path>
	<g>
		<path fill="#FFD633" d="M90.169,216.275c-0.408,0-0.948-0.336-1.096-0.688c-0.116-0.282-0.359-0.874,1.049-2.272l45.011-45.002
			c0.789-0.787,1.175-1.924,1.028-3.029c-0.147-1.101-0.813-2.098-1.778-2.649l-31.101-17.896c-1.089-0.625-1.73-1.579-1.715-2.552
			c0.016-0.967,0.688-1.896,1.796-2.481l104.732-55.388c0.998-0.53,1.46-0.599,1.76-0.599c0.412,0,0.914,0.318,1.059,0.664
			c0.139,0.327,0.385,0.91-1.03,2.319l-44.915,44.915c-0.789,0.783-1.17,1.911-1.027,3.018c0.145,1.106,0.809,2.098,1.768,2.652
			l31.05,17.966c1.07,0.62,1.702,1.567,1.679,2.53c-0.017,0.984-0.684,1.916-1.777,2.502L91.909,215.689
			C90.92,216.219,90.46,216.275,90.169,216.275z"></path>
	</g>
</g>
</svg>`},
}

var userCreateSQLOptions = []userCreateOption{
	{Value: "mysql", Label: "MySQL", Description: "The most widely used open-source database, with broad compatibility and tooling support.",
		Icon: `<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="w-16 h-16" aria-label="MySQL"><title>MySQL</title><path fill="#003545" d="M16.405 5.501c-.115 0-.193.014-.274.033v.013h.014c.054.104.146.18.214.273.054.107.1.214.154.32l.014-.015c.094-.066.14-.172.14-.333-.04-.047-.046-.094-.08-.14-.04-.067-.126-.1-.18-.153zM5.77 18.695h-.927a50.854 50.854 0 00-.27-4.41h-.008l-1.41 4.41H2.45l-1.4-4.41h-.01a72.892 72.892 0 00-.195 4.41H0c.055-1.966.192-3.81.41-5.53h1.15l1.335 4.064h.008l1.347-4.064h1.095c.242 2.015.384 3.86.428 5.53zm4.017-4.08c-.378 2.045-.876 3.533-1.492 4.46-.482.716-1.01 1.073-1.583 1.073-.153 0-.34-.046-.566-.138v-.494c.11.017.24.026.386.026.268 0 .483-.075.647-.222.197-.18.295-.382.295-.605 0-.155-.077-.47-.23-.944L6.23 14.615h.91l.727 2.36c.164.536.233.91.205 1.123.4-1.064.678-2.227.835-3.483zm12.325 4.08h-2.63v-5.53h.885v4.85h1.745zm-3.32.135l-1.016-.5c.09-.076.177-.158.255-.25.433-.506.648-1.258.648-2.253 0-1.83-.718-2.746-2.155-2.746-.704 0-1.254.232-1.65.697-.43.508-.646 1.256-.646 2.245 0 .972.19 1.686.574 2.14.35.41.877.615 1.583.615.264 0 .506-.033.725-.098l1.325.772.36-.622zM15.5 17.588c-.225-.36-.337-.94-.337-1.736 0-1.393.424-2.09 1.27-2.09.443 0 .77.167.977.5.224.362.336.936.336 1.723 0 1.404-.424 2.108-1.27 2.108-.445 0-.77-.167-.978-.5zm-1.658-.425c0 .47-.172.856-.516 1.156-.344.3-.803.45-1.384.45-.543 0-1.064-.172-1.573-.515l.237-.476c.438.22.833.328 1.19.328.332 0 .593-.073.783-.22a.754.754 0 00.3-.615c0-.33-.23-.61-.648-.845-.388-.213-1.163-.657-1.163-.657-.422-.307-.632-.636-.632-1.177 0-.45.157-.81.47-1.085.315-.278.72-.415 1.22-.415.512 0 .98.136 1.4.41l-.213.476a2.726 2.726 0 00-1.064-.23c-.283 0-.502.068-.654.206a.685.685 0 00-.248.524c0 .328.234.61.666.85.393.215 1.187.67 1.187.67.433.305.648.63.648 1.168zm9.382-5.852c-.535-.014-.95.04-1.297.188-.1.04-.26.04-.274.167.055.053.063.14.11.214.08.134.218.313.346.407.14.11.28.216.427.31.26.16.555.255.81.416.145.094.293.213.44.313.073.05.12.14.214.172v-.02c-.046-.06-.06-.147-.105-.214-.067-.067-.134-.127-.2-.193a3.223 3.223 0 00-.695-.675c-.214-.146-.682-.35-.77-.595l-.013-.014c.146-.013.32-.066.46-.106.227-.06.435-.047.67-.106.106-.027.213-.06.32-.094v-.06c-.12-.12-.21-.283-.334-.395a8.867 8.867 0 00-1.104-.823c-.21-.134-.476-.22-.697-.334-.08-.04-.214-.06-.26-.127-.12-.146-.19-.34-.275-.514a17.69 17.69 0 01-.547-1.163c-.12-.262-.193-.523-.34-.763-.69-1.137-1.437-1.826-2.586-2.5-.247-.14-.543-.2-.856-.274-.167-.008-.334-.02-.5-.027-.11-.047-.216-.174-.31-.235-.38-.24-1.364-.76-1.644-.072-.18.434.267.862.422 1.082.115.153.26.328.34.5.047.116.06.235.107.356.106.294.207.622.347.897.073.14.153.287.247.413.054.073.146.107.167.227-.094.136-.1.334-.154.5-.24.757-.146 1.693.194 2.25.107.166.362.534.703.393.3-.12.234-.5.32-.835.02-.08.007-.133.048-.187v.015c.094.188.188.367.274.555.206.328.566.668.867.895.16.12.287.328.487.402v-.02h-.015c-.043-.058-.1-.086-.154-.133a3.445 3.445 0 01-.35-.4 8.76 8.76 0 01-.747-1.218c-.11-.21-.202-.436-.29-.643-.04-.08-.04-.2-.107-.24-.1.146-.247.273-.32.453-.127.288-.14.642-.188 1.01-.027.007-.014 0-.027.014-.214-.052-.287-.274-.367-.46-.2-.475-.233-1.238-.06-1.785.047-.14.247-.582.167-.716-.042-.127-.174-.2-.247-.303a2.478 2.478 0 01-.24-.427c-.16-.374-.24-.788-.414-1.162-.08-.173-.22-.354-.334-.513-.127-.18-.267-.307-.368-.52-.033-.073-.08-.194-.027-.274.014-.054.042-.075.094-.09.088-.072.335.022.422.062.247.1.455.194.662.334.094.066.195.193.315.226h.14c.214.047.455.014.655.073.355.114.675.28.962.46a5.953 5.953 0 012.085 2.286c.08.154.115.295.188.455.14.33.313.663.455.982.14.315.275.636.476.897.1.14.502.213.682.286.133.06.34.115.46.188.23.14.454.3.67.454.11.076.443.243.463.378z"/></svg>`},
	{Value: "mariadb", Label: "MariaDB", Description: "A community-developed fork of MySQL with extra storage engines and performance tweaks.",
		Icon: `<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="w-16 h-16" aria-label="MariaDB"><title>MariaDB</title><path fill="#003545" d="M23.157 4.412c-.676.284-.79.31-1.673.372-.65.045-.757.057-1.212.209-.75.246-1.395.75-2.02 1.59-.296.398-1.249 1.913-1.249 1.988 0 .057-.65.998-.915 1.32-.574.713-1.08 1.079-2.14 1.59-.77.36-1.224.524-4.102 1.477-1.073.353-2.133.738-2.367.864-.852.449-1.515 1.036-2.203 1.938-1.003 1.32-.972 1.313-3.042.947a12.264 12.264 0 00-.675-.063c-.644-.05-1.023.044-1.332.334L0 17.193l.177.088c.094.05.353.234.561.398.215.17.461.347.55.391.088.044.17.088.183.101.012.013-.089.17-.228.353-.435.581-.593.871-.574 1.048.019.164.032.17.43.17.517-.006.826-.056 1.261-.208.65-.233 2.058-.94 2.784-1.4.776-.5 1.717-.998 1.956-1.042.082-.02.354-.07.594-.114.58-.107 1.464-.095 2.587.05.108.013.373.045.6.064.227.025.43.057.454.076.026.012.474.037.998.056.934.026 1.104.007 1.3-.189.126-.133.385-.631.498-.985.209-.643.417-.921.366-.492-.113.966-.322 1.692-.713 2.411-.259.499-.663 1.092-.934 1.395-.322.347-.315.36.088.315.619-.063 1.471-.397 2.096-.82.827-.562 1.647-1.691 2.19-3.03.107-.27.22-.22.183.083-.013.094-.038.315-.057.498l-.031.328.353-.202c.833-.48 1.414-1.262 2.127-2.884.227-.518.877-2.922 1.073-3.976a9.64 9.64 0 01.271-1.042c.127-.429.196-.555.48-.858.183-.19.625-.555.978-.808.72-.505.953-.75 1.187-1.205.208-.417.284-1.13.132-1.357-.132-.202-.284-.196-.763.006Z"/></svg>`},
}

// readUserCreateDefaultsEnv is a distinct, simpler helper from defaults.go's
// readDefaultsEnvGroups() -- it only cares about
// WEB_SERVER/MYSQL_TYPE/VARNISH, reading the same .env file at
// DefaultsEnvPath (defaults.go).
func readUserCreateDefaultsEnv() (webServer, mysqlType string, varnish bool) {
	raw, err := os.ReadFile(DefaultsEnvPath)
	if err != nil {
		return "", "", false
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(line, "MYSQL_TYPE="):
			mysqlType = strings.Trim(strings.TrimPrefix(line, "MYSQL_TYPE="), `"'`)
		case strings.HasPrefix(line, "WEB_SERVER="):
			webServer = strings.Trim(strings.TrimPrefix(line, "WEB_SERVER="), `"'`)
		case strings.HasPrefix(line, "PROXY_HTTP_PORT="):
			varnish = true
		case strings.HasPrefix(line, "#PROXY_HTTP_PORT="):
			varnish = false
		}
	}
	return
}

// ServeCreateUser handles GET/POST /user/new.
func (u *Users) ServeCreateUser(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodPost {
		u.handleCreateUserPost(w, r)
		return
	}

	resellerOwner := u.resellerScope(r)
	var allowed []int
	if resellerOwner != "" {
		if ids, ok := paneldb.AllowedPlansForReseller(resellerOwner); ok {
			allowed = ids
		}
	}
	plans, err := paneldb.GetAllPlans(u.MySQL, allowed)
	mysqlIsDown := err != nil

	webServer, mysqlType, varnish := readUserCreateDefaultsEnv()

	webtemplates.Render(w, "user_add.html", userCreatePageData{
		Chrome:           buildChrome(r, "Add User"),
		Plans:            plans,
		MySQLIsDown:      mysqlIsDown,
		WebServer:        webServer,
		MySQLType:        mysqlType,
		VarnishEnabled:   varnish,
		Webservers:       userCreateWebservers,
		SQLOptions:       userCreateSQLOptions,
		ResellersEnabled: resellersEnabled(),
		CSRFToken:        csrf.Token(r),
		Flashes:          auth.PopFlashes(w, r, u.Sessions),
	})
}

var userCreateIPv4Re = regexp.MustCompile(`^\d+\.\d+\.\d+\.\d+$`)

// userCreateRun is injectable so tests never shell out to a real opencli
// binary.
var userCreateRun = func(args []string) (*exec.Cmd, error) {
	return exec.Command(args[0], args[1:]...), nil
}

// handleCreateUserPost builds the `opencli user-add` argv from the
// submitted form and streams its stdout back line-by-line as it runs.
func (u *Users) handleCreateUserPost(w http.ResponseWriter, r *http.Request) {
	// The form is submitted as multipart/form-data (the frontend posts a
	// FormData body), not application/x-www-form-urlencoded, so it must be
	// parsed with ParseMultipartForm -- plain ParseForm leaves the body
	// unread for that content type and PostFormValue silently returns "".
	_ = r.ParseMultipartForm(32 << 20)

	email := r.PostFormValue("admin_email")
	username := strings.ToLower(r.PostFormValue("admin_username"))
	password := r.PostFormValue("admin_password")
	planName := r.PostFormValue("plan_name")
	sendMail := r.PostFormValue("send_email")
	webserver := r.PostFormValue("webserver")
	mysqlType := r.PostFormValue("sql_type")
	reseller := r.PostFormValue("reseller")
	slave := r.PostFormValue("slave")
	sshKeyPath := r.PostFormValue("ssh_key_path")

	if email == "" {
		email = username
	}

	command := []string{"opencli", "user-add", username, password, email, planName, "--debug"}

	currentUser := auth.CurrentUser(r)
	if currentUser != nil && currentUser.Role == "reseller" {
		command = append(command, "--reseller="+currentUser.Username)
	} else if reseller != "" {
		command = append(command, "--reseller="+reseller)
	}

	if webserver != "" {
		base := strings.TrimPrefix(strings.ToLower(webserver), "varnish+")
		switch base {
		case "apache", "nginx", "openresty", "openlitespeed":
			command = append(command, "--webserver="+webserver)
		}
	}

	if mysqlType != "" {
		if lower := strings.ToLower(mysqlType); lower == "mysql" || lower == "mariadb" {
			command = append(command, "--sql="+mysqlType)
		}
	}

	if sendMail != "" {
		command = append(command, "--send-email")
	}

	if slave != "" && userCreateIPv4Re.MatchString(slave) {
		command = append(command, "--server="+slave)
	}

	if sshKeyPath != "" {
		command = append(command, "--key="+sshKeyPath)
	}

	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "Streaming unsupported", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/event-stream")

	if slave != "" && sshKeyPath == "" {
		fmt.Fprintf(w, "Error: SSH key path is required for creating account on %s\n", slave)
		flusher.Flush()
		return
	}

	cmd, err := userCreateRun(command)
	if err != nil {
		fmt.Fprintf(w, "Error: %s\n\n", err.Error())
		flusher.Flush()
		return
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		fmt.Fprintf(w, "Error: %s\n\n", err.Error())
		flusher.Flush()
		return
	}
	// Only stdout is read line-by-line and streamed to the client; stderr
	// is never read from here -- any output opencli sends to stderr is
	// silently discarded, not a bug to "fix" here.
	if err := cmd.Start(); err != nil {
		fmt.Fprintf(w, "Error: %s\n\n", err.Error())
		flusher.Flush()
		return
	}
	scanner := bufio.NewScanner(stdout)
	for scanner.Scan() {
		fmt.Fprintf(w, "%s\n", strings.TrimSpace(scanner.Text()))
		flusher.Flush()
	}
	if err := cmd.Wait(); err != nil {
		fmt.Fprintf(w, "Error: %s\n", err.Error())
		flusher.Flush()
	}
}

func logUserAction(username, ip, action string) {
	username = stripSuspendedPrefix(username)
	username = strings.ReplaceAll(username, " ", "")
	logDir := "/etc/openpanel/openpanel/core/users/" + username
	if err := os.MkdirAll(logDir, 0755); err != nil {
		return
	}
	f, err := os.OpenFile(logDir+"/activity.log", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return
	}
	defer f.Close()
	timestamp := time.Now().Format("2006-01-02 15:04:05")
	_, _ = f.WriteString(timestamp + "  " + ip + " " + action + "\n")
}

// ServeResourceUsageHistory handles GET
// /get_resource_usage_history/{username}: the raw, unparsed contents of the
// user's resource_usage.txt file (every historical JSONL snapshot line, not
// just the last one like readUsageStatsFor/ServeDetail use) -- served as
// plain text, NOT JSON, despite what the route's name might suggest.
func (u *Users) ServeResourceUsageHistory(w http.ResponseWriter, r *http.Request) {
	username := stripSuspendedPrefix(r.PathValue("username"))
	currentUser := auth.CurrentUser(r)

	if !paneldb.CheckIfOwnerForUser(u.MySQL, username, currentUser.Username, currentUser.Role) {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return
	}

	context, _ := queryContextByUsername(u.MySQL, username)
	raw, err := os.ReadFile("/home/" + context + "/resource_usage.txt")
	if err != nil {
		http.Error(w, "Resource usage file not found.", http.StatusNotFound)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Write(raw)
}

// userDiskInfoRun is injectable so tests never shell out to a real podman
// binary. Runs `podman system df --format {{json .}}` (summary, not -v --
// podman rejects combining --verbose with --format), whose stdout is one
// independent per-type JSON object per line (Images/Containers/Local
// Volumes/Build Cache, each with Type/Total/Active/Size/Reclaimable).
var userDiskInfoRun = func(context string) (stdout, stderr string, exitCode int, err error) {
	return podmanExecCapture(context, "system", "df", "--format", "{{json .}}")
}

// ServeUserDiskInfo handles GET /client/disk/{username}. Note: unlike most
// other routes in this file, this never strips a "SUSPENDED_..." prefix
// from username here before the ownership check or the context lookup --
// preserved as-is rather than made consistent with the other routes.
func (u *Users) ServeUserDiskInfo(w http.ResponseWriter, r *http.Request) {
	username := r.PathValue("username")
	currentUser := auth.CurrentUser(r)

	if !paneldb.CheckIfOwnerForUser(u.MySQL, username, currentUser.Username, currentUser.Role) {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return
	}

	context, _ := queryContextByUsername(u.MySQL, username)
	stdout, stderr, exitCode, err := userDiskInfoRun(context)
	if err != nil {
		writeJSONStatus(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if exitCode != 0 {
		writeJSONStatus(w, http.StatusInternalServerError, map[string]string{
			"error": fmt.Sprintf("podman system df exited with status %d: %s", exitCode, strings.TrimSpace(stderr)),
		})
		return
	}

	data := []json.RawMessage{}
	for _, line := range strings.Split(strings.TrimSpace(stdout), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if !json.Valid([]byte(line)) {
			writeJSONStatus(w, http.StatusInternalServerError, map[string]string{"error": "invalid JSON in podman output"})
			return
		}
		data = append(data, json.RawMessage(line))
	}
	writeJSON(w, data)
}

// userLogConfig describes one type of user log (activity or logins).
type userLogConfig struct {
	Filename       string
	DownloadSuffix string
	Key            string
	Pattern        *regexp.Regexp
	Fields         []string // nil means the pattern uses named groups instead
}

// userLogConfigs maps each supported log type to its config.
var userLogConfigs = map[string]userLogConfig{
	"activity": {
		Filename:       "activity.log",
		DownloadSuffix: "activity",
		Key:            "user_activity",
		Pattern:        regexp.MustCompile(`^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\s+(\d+\.\d+\.\d+\.\d+)\s+(User|Administrator)\s+(\S+)\s+(.*)`),
		Fields:         []string{"timestamp", "ip_address", "user_type", "user", "action"},
	},
	"logins": {
		Filename:       ".lastlogin",
		DownloadSuffix: "logins",
		Key:            "user_logins",
		Pattern:        regexp.MustCompile(`^IP:\s*(?P<ip>[\d.]+)\s*-\s*Country:\s*(?P<country>\w+)\s*-\s*Login Time:\s*(?P<login_time>[\d\-\s:]+)`),
	},
}

// parseGenericUserLogLine parses one log line using a config's regex
// pattern and field names.
func parseGenericUserLogLine(line string, conf userLogConfig) map[string]string {
	m := conf.Pattern.FindStringSubmatch(line)
	if m == nil {
		return nil
	}
	out := map[string]string{}
	if conf.Fields != nil {
		for i, f := range conf.Fields {
			out[f] = m[i+1]
		}
		return out
	}
	for i, name := range conf.Pattern.SubexpNames() {
		if i == 0 || name == "" {
			continue
		}
		out[name] = m[i]
	}
	return out
}

// capitalizeFirst is good enough for this file's two log_type values
// ("activity"/"logins"): uppercase the first rune, lowercase the rest.
func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}

// getParsedUserLogJSON returns the reversed (newest-first), regex-parsed
// lines of the user's log file. Its "Log not found" message deliberately
// does NOT mention log_type -- unlike the raw/download 404 branches in
// ServeUserLog below, which do -- since the two code paths handle the
// missing-file case independently and were never unified.
func getParsedUserLogJSON(username string, conf userLogConfig) (int, map[string]interface{}) {
	path := "/etc/openpanel/openpanel/core/users/" + username + "/" + conf.Filename
	raw, err := os.ReadFile(path)
	if err != nil {
		return http.StatusNotFound, map[string]interface{}{"error": "Log not found"}
	}
	lines := strings.Split(string(raw), "\n")
	parsed := []map[string]string{}
	for i := len(lines) - 1; i >= 0; i-- {
		line := strings.TrimSpace(lines[i])
		if line == "" {
			continue
		}
		if p := parseGenericUserLogLine(line, conf); p != nil {
			parsed = append(parsed, p)
		}
	}
	return http.StatusOK, map[string]interface{}{conf.Key: parsed}
}

// ServeUserLog handles GET /json/{userLogType}/{username}. The route is
// meant to serve /json/user-<log_type>/<username> URLs (a literal "user-"
// prefix fused directly onto the <log_type> URL segment), but Go's
// ServeMux can't express a literal-prefix-then-wildcard within one path
// segment, so the "user-" is matched as part of a whole {userLogType}
// segment here and stripped/validated inside the handler instead. The set
// of real reachable URLs is identical, and this doesn't collide with GET
// /json/{resource} since that pattern has one fewer path segment.
func (u *Users) ServeUserLog(w http.ResponseWriter, r *http.Request) {
	rawSegment := r.PathValue("userLogType")
	logType, ok := strings.CutPrefix(rawSegment, "user-")
	if !ok {
		http.NotFound(w, r)
		return
	}
	conf, ok := userLogConfigs[logType]
	if !ok {
		http.NotFound(w, r)
		return
	}

	username := stripSuspendedPrefix(r.PathValue("username"))
	currentUser := auth.CurrentUser(r)
	if !paneldb.CheckIfOwnerForUser(u.MySQL, username, currentUser.Username, currentUser.Role) {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return
	}

	logFilePath := "/etc/openpanel/openpanel/core/users/" + username + "/" + conf.Filename
	download := strings.EqualFold(r.URL.Query().Get("download"), "true")
	rawWanted := strings.EqualFold(r.URL.Query().Get("raw"), "true")

	if download {
		data, err := os.ReadFile(logFilePath)
		if err != nil {
			writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": capitalizeFirst(logType) + " log not found"})
			return
		}
		filename := fmt.Sprintf("%s_%s_%s.log", username, conf.DownloadSuffix, time.Now().Format("2006-01-02_15-04-05"))
		w.Header().Set("Content-Type", "text/plain")
		w.Header().Set("Content-Disposition", `attachment; filename="`+filename+`"`)
		w.Write(data)
		return
	}

	if rawWanted {
		data, err := os.ReadFile(logFilePath)
		if err != nil {
			writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": capitalizeFirst(logType) + " log not found"})
			return
		}
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Write(data)
		return
	}

	status, body := getParsedUserLogJSON(username, conf)
	writeJSONStatus(w, status, body)
}

// HandleCustomMessage handles GET/POST
// /get_custom_message_for_user/{username}. Note: like ServeUserDiskInfo
// above, this never strips a "SUSPENDED_..." prefix from username here.
func (u *Users) HandleCustomMessage(w http.ResponseWriter, r *http.Request) {
	username := r.PathValue("username")
	currentUser := auth.CurrentUser(r)

	if !paneldb.CheckIfOwnerForUser(u.MySQL, username, currentUser.Username, currentUser.Role) {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return
	}

	path := "/etc/openpanel/openpanel/core/users/" + username + "/custom_message.html"

	if r.Method == http.MethodPost {
		var body struct {
			CustomMessage *string `json:"custom_message"`
		}
		if json.NewDecoder(r.Body).Decode(&body) != nil {
			writeJSONError(w, http.StatusBadRequest, "Invalid content type. Expected JSON.")
			return
		}
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			writeJSONError(w, http.StatusInternalServerError, "Failed to save custom message")
			return
		}
		if body.CustomMessage != nil && *body.CustomMessage != "" {
			os.WriteFile(path, []byte(*body.CustomMessage), 0644)
			writeJSON(w, map[string]string{"message": "Custom message for user " + username + " saved successfully."})
		} else {
			// An empty/missing custom_message doesn't delete the file, it
			// overwrites it with empty content.
			os.WriteFile(path, []byte(""), 0644)
			writeJSON(w, map[string]string{"message": "Custom message for user " + username + " deleted successfully."})
		}
		return
	}

	if raw, err := os.ReadFile(path); err == nil {
		writeJSON(w, map[string]string{"custom_message": string(raw)})
		return
	}
	writeJSON(w, map[string]string{"message": "No custom message found"})
}
